apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Manabu
  description: An example of a Backstage application.
    - url: https://github.com/${{values.owner + "/" + values.name}}
      title: Backstage Repo
      icon: github
  # Example for optional annotations
  annotations:
    github.com/project-slug: ${{values.owner + "/" + values.name}}
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: ${{values.owner}}
  lifecycle: experimental
